# Generated by Django 4.2.1 on 2023-06-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="item_images"),
        ),
    ]
