# Generated by Django 4.2.2 on 2023-06-16 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item", "0005_item_was_owned_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="was_owned_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
